### ISSUE TITLE
The subejct "fenghaohan.tar.gz" are broken！

### ISSUE THREAD

**Issue by JanaldoChen** [generalizable-neural-performer/gnr#11]
When I run the command "tar -xvf fenghaohan.tar.gz", I met this error:
<img width="451" alt="image" src="https://user-images.githubusercontent.com/44859515/193254380-7c642aab-2617-45a0-9bf4-139096ceb1e4.png">

**Comment by dsvilarkovic** [comment]
It's not broken you just didn't download the full file from their link since it's a large file and you are probably downloading directly from a browser . I suggest following their data downloading script genebody/download_tool.py and tweaking filesData in line 230/231 to select only datasets you are looking for, this way you should get a full subject.

**Comment by JanaldoChen** [comment]
OK, thanks！I downloaded it by script *genebody/download_tool.py*
